# Generated by Django 2.2 on 2019-04-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='0x0', max_length=42)),
                ('side', models.IntegerField(default=1)),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('filled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markets.Market')),
            ],
        ),
    ]
