# Generated by Django 2.2 on 2019-04-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('orders', '0002_auto_20190406_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ticker',
        ),
        migrations.AddField(
            model_name='order',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Market'),
        ),
    ]
