# Generated by Django 2.2 on 2019-04-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('side', models.IntegerField(choices=[(1, 'BUY'), (0, 'SELL')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'NEW'), (1, 'PROCESSING'), (2, 'OK'), (3, 'REJECTED')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_buy', to='orders.Order')),
                ('order_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sell', to='orders.Order')),
            ],
        ),
    ]
