# Generated by Django 2.2 on 2019-04-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
