# Generated by Django 2.2 on 2019-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.IntegerField(choices=[(0, 'NEW'), (1, 'PROCESSING'), (2, 'OK'), (3, 'REJECTED')], default=0),
        ),
    ]
