# Generated by Django 2.2 on 2019-04-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20190406_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('side', models.IntegerField(choices=[(1, 'BUY'), (0, 'SELL')], default=0)),
                ('order_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_buy', to='orders.Order')),
                ('order_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sell', to='orders.Order')),
            ],
        ),
    ]
