# Generated by Django 2.2 on 2019-04-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(default=0)),
                ('side', models.IntegerField(choices=[(1, 'BUY'), (0, 'SELL')], default=1)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=40)),
                ('size', models.DecimalField(decimal_places=0, default=0, max_digits=40)),
                ('filled', models.DecimalField(decimal_places=0, default=0, max_digits=40)),
                ('status', models.IntegerField(default=0)),
                ('hash_signature', models.CharField(default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='markets.Market')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
