# Generated by Django 2.2 on 2019-04-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='markets.Market'),
        ),
    ]
