# Generated by Django 2.2 on 2019-04-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190407_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_set', to='markets.Market'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.IntegerField(choices=[(1, 'BUY'), (0, 'SELL')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=40),
        ),
    ]
